In [1]:
import pandas as pd

In [2]:
import csv as csv

In [3]:
housing_data = pd.read_csv('USA_Housing.csv')

In [4]:
housing_data.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562388,5.322283,6.299250,3.140000,29403.928702,9.975771e+05
50%,68804.286404,5.970429,7.002902,4.050000,36199.406689,1.232669e+06
75%,75783.338666,6.650808,7.665871,4.490000,42861.290769,1.471210e+06
max,107701.748378,9.519088,10.759588,6.500000,69621.713378,2.469066e+06

In [6]:
housing_data.shape

(5000, 7)

In [8]:
housing_data.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [18]:
# - Income and Ages for population > 50K
housing_data[housing_data['Area Population'] > 50000][['Avg. Area Income', 'Avg. Area House Age', 'Area Population']]

      Avg. Area Income  Avg. Area House Age  Area Population
6         64698.463428             6.025336     60828.249085
53        73078.204086             5.923906     54915.961782
64        59539.948450             6.018590     58600.827150
77        64826.371895             4.010907     60286.043101
83        80659.525444             5.436306     52947.036360
95        73698.696357             6.372731     51815.096419
117       73923.466274             7.005506     58745.312028
128       44806.005164             4.494571     57390.890074
144       47681.361733             6.890508     50908.978909
181       65316.996021             7.414875     55799.497481
208       51273.508853             7.032317     53811.894906
222       61978.848046             7.912276     56957.187750
228       66574.709994             5.550265     69575.449464
231       58088.438130             6.017831     51925.411613
239       60081.176620             6.768524     60195.746267
243       72175.283499             7.421739     50305.795413
256       91159.418327             6.536045     54861.091097
259       63183.889742             5.570562     58691.200665
286       69017.182800             5.777106     55830.752836
297       73225.066295             5.933499     61830.539722
306       59243.297630             6.729521     51405.352484
341       72988.705969             5.959379     50566.644799
353       72445.033303             5.488197     69553.988327
379       56231.161796             5.459845     52657.033754
419       73756.118624             5.250631     59485.066323
424       58557.131282             5.302173     54167.341625
426       69807.723356             7.424253     51453.265163
428       97112.361252             5.914725     51470.067638
433       66484.048195             4.825804     51712.144087
439       64038.993885             4.025768     54130.975953
...                ...                  ...              ...
4664      66397.440987             4.835749     50504.047824
4682      91935.366852             6.483291     50112.820224
4692      62785.911645             6.759944     59003.963621
4701      74952.963986             5.143167     50373.832886
4705      57084.301020             7.255851     55851.847190
4716      38530.124478             4.265906     67727.229051
4734      46449.625640             6.573053     55176.202553
4737      86962.957716             6.520076     50350.959219
4753      54629.085713             4.114407     55495.031974
4766      66565.728724             6.634228     50182.398381
4786      67043.212293             4.876857     62402.742391
4788      74665.967604             4.808296     59036.116037
4794      57679.760164             6.019769     53494.945556
4803      61846.135900             5.057578     69621.713378
4833      61000.160428             6.691542     60697.639241
4856      60850.702061             3.690574     56303.305988
4868      53362.686295             7.535711     50304.748315
4875      58676.411529             5.978277     56269.462943
4910      57699.658481             7.004416     60849.316862
4922      79522.970805             4.590628     61223.997607
4931      77622.958116             6.738014     51102.441950
4933      52848.630468             5.329908     53628.682388
4935      60041.207007             3.989951     50637.874107
4947      58566.399723             5.595077     53152.349473
4957      61641.054275             7.428646     50035.747633
4959      75078.791516             7.644779     56148.449322
4979      82224.695006             5.434087     57166.867510
4980      75664.024482             5.789203     54724.251275
4984      62623.359828             5.071624     50985.971202
4993      69639.140896             5.007510     54056.128430

[395 rows x 3 columns]

In [19]:
housing_data[housing_data['Area Population'] > 50000][['Avg. Area Income', 'Avg. Area House Age', 'Area Population']].rename(columns = {'Avg. Area Income': 'Avg_Income'})
#housing_data.rename(columns = {'y':'year'})

        Avg_Income  Avg. Area House Age  Area Population
6     64698.463428             6.025336     60828.249085
53    73078.204086             5.923906     54915.961782
64    59539.948450             6.018590     58600.827150
77    64826.371895             4.010907     60286.043101
83    80659.525444             5.436306     52947.036360
95    73698.696357             6.372731     51815.096419
117   73923.466274             7.005506     58745.312028
128   44806.005164             4.494571     57390.890074
144   47681.361733             6.890508     50908.978909
181   65316.996021             7.414875     55799.497481
208   51273.508853             7.032317     53811.894906
222   61978.848046             7.912276     56957.187750
228   66574.709994             5.550265     69575.449464
231   58088.438130             6.017831     51925.411613
239   60081.176620             6.768524     60195.746267
243   72175.283499             7.421739     50305.795413
256   91159.418327             6.536045     54861.091097
259   63183.889742             5.570562     58691.200665
286   69017.182800             5.777106     55830.752836
297   73225.066295             5.933499     61830.539722
306   59243.297630             6.729521     51405.352484
341   72988.705969             5.959379     50566.644799
353   72445.033303             5.488197     69553.988327
379   56231.161796             5.459845     52657.033754
419   73756.118624             5.250631     59485.066323
424   58557.131282             5.302173     54167.341625
426   69807.723356             7.424253     51453.265163
428   97112.361252             5.914725     51470.067638
433   66484.048195             4.825804     51712.144087
439   64038.993885             4.025768     54130.975953
...            ...                  ...              ...
4664  66397.440987             4.835749     50504.047824
4682  91935.366852             6.483291     50112.820224
4692  62785.911645             6.759944     59003.963621
4701  74952.963986             5.143167     50373.832886
4705  57084.301020             7.255851     55851.847190
4716  38530.124478             4.265906     67727.229051
4734  46449.625640             6.573053     55176.202553
4737  86962.957716             6.520076     50350.959219
4753  54629.085713             4.114407     55495.031974
4766  66565.728724             6.634228     50182.398381
4786  67043.212293             4.876857     62402.742391
4788  74665.967604             4.808296     59036.116037
4794  57679.760164             6.019769     53494.945556
4803  61846.135900             5.057578     69621.713378
4833  61000.160428             6.691542     60697.639241
4856  60850.702061             3.690574     56303.305988
4868  53362.686295             7.535711     50304.748315
4875  58676.411529             5.978277     56269.462943
4910  57699.658481             7.004416     60849.316862
4922  79522.970805             4.590628     61223.997607
4931  77622.958116             6.738014     51102.441950
4933  52848.630468             5.329908     53628.682388
4935  60041.207007             3.989951     50637.874107
4947  58566.399723             5.595077     53152.349473
4957  61641.054275             7.428646     50035.747633
4959  75078.791516             7.644779     56148.449322
4979  82224.695006             5.434087     57166.867510
4980  75664.024482             5.789203     54724.251275
4984  62623.359828             5.071624     50985.971202
4993  69639.140896             5.007510     54056.128430

[395 rows x 3 columns]